Add elasticsearch template parameters
kokuwaio/helm-charts pull request #31
Opened 2020-11-24 00:01 UTC by moreinhardt

To fix ILM policy creation logic.

# Which chart
fluentd-elasticsearch

# What this PR does / why we need it
It actually makes the ILM features of the elasticsearch plugin usable in this chart.

# Which issue this PR fixes
* fixes #17 
* relates to https://github.com/kiwigrid/helm-charts/issues/396

# Special notes for your reviewer
* With these changes an index template and an ILM policy are created and the indices are attached even with logstash enabled.
* I did not try this without logstash enabled.
* Since these template parameters should always be supplied if ILM is enabled, I use this condition.
* But the index template could also be used without ILM so this is possible too.
* I am not sure if the parameter `elasticsearch.template.file` should even be modifiable through `values.yaml` as that's really just the name of the file _inside_ the daemonset pod.
* This should probably be documented better than just in this simple table in the README. I could add a section below that.

# Checklist

- [ ] [DCO](https://github.com/kokuwaio/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] All variables are documented in the charts README

pinging owner according to guidelines :slightly_smiling_face: @monotek

2020-11-24 09:03 UTC, moreinhardt commented
I would sign off my commits but for that I would need to rebase them - shall I proceed?

Also, I would rebase this branch on your master to avoid having these merges on the feature branch, ok?

2020-11-25 00:29 UTC, monotek requested changes
please sign your commits to fix the dco check

2020-11-25 10:27 UTC, moreinhardt commented
Rebased to sign DCO and remove merge commits. :-)

2020-11-25 12:51 UTC, monotek approved these changes

2020-11-25 12:52 UTC, merged