introduced variable fluentConfDir in order to configure conf location
kokuwaio/helm-charts pull request #36
Opened 2020-12-01 13:09 UTC by etiennejournet

# Which chart

Fluentd-elasticsearch

# What this PR does / why we need it

add variable in order to configure fluent conf location

# Special notes for your reviewer

# Checklist

- [ ] [DCO](https://github.com/kokuwaio/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [X ] Chart Version bumped
- [ ] All variables are documented in the charts README

2020-12-01 13:35 UTC, etiennejournet commented
Need it to use other fluent-daemonset images (e.g kafka) with your helm chart

2020-12-02 00:28 UTC, monotek requested changes

2020-12-02 00:28 UTC, monotek commented on charts/fluentd-elasticsearch/Chart.yaml
> +version: 11.1.1
minor version should be raised for feature update.

2020-12-02 15:46 UTC, monotek approved these changes

2020-12-02 15:46 UTC, merged

2020-12-03 11:36 UTC, etiennejournet commented
thanks a lot