[fluentd-elasticsearch] Fix liveness probe logic to detect stuck elasticsearch buffers
kokuwaio/helm-charts pull request #71
Opened 2021-04-09 18:21 UTC by Ghazgkull

# Which chart

fluentd-elasticsearch

# What this PR does / why we need it

This PR fixes a logic defect in the liveness probe for fluentd-elasticsearch, which causes fluentd pods deployed by this helm chart to be periodically killed needlessly. In environments with monitoring and alerting configured, this problem results in frequent alerts about fluentd being restarted.

Before this change, the liveness probe says:
```if [ -z "$(find /var/log/fluentd-buffers -type d -newer /tmp/marker-stuck -print -quit)" ];```

This line tries to find buffers that are newer than the "stuck" marker file. If it doesn't find any (`-z` for empty string), it assumes that this means the buffer files are all older than the stuck marker and it causes liveness to fail. This logic *will* work to fail the liveness probe if there are stuck buffers. But it will also fail the liveness probe if there are *no* buffers, which is wrong.

After the change, the liveness probe says:
```if [ -n "$(find /var/log/fluentd-buffers -mindepth 1 -type d ! -newer /tmp/marker-stuck -print -quit)" ];```

This line looks for any files under the fluentd-buffers directory which are older (`! newer` - NOT newer) than the stuck marker and fails if any are found (`-n` non-empty string). The `-mindepth 1` tells `find` not to include the parent directory /var/log/fluentd-buffers itself. This logic will work to fail the liveness probe if there are stuck buffers. It will *not* fail the liveness prove if there are no buffers, which happens in low-volume situations.

This PR also adds `echo` statements to the failures, which greatly improves debuggability for Kubernetes operators. By adding this output, Kubernetes will include it on the Events which report the pod being killed.

# Which issue this PR fixes

- fixes #70 

# Special notes for your reviewer

# Checklist

- [x] [DCO](https://github.com/kokuwaio/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] All variables are documented in the charts README

2021-04-09 18:22 UTC, Ghazgkull commented
@monotek Please consider this PR, which fixes an issue with the liveness probe.

2021-04-09 20:10 UTC, monotek approved these changes

2021-04-09 20:13 UTC, monotek commented
Thanks for the pr. I'll fix the lint problem tomorrow....

Or if you like... The checkout step needs a:

```
with:
          fetch-depth: 0
```

2021-04-09 20:24 UTC, Ghazgkull commented
@monotek I've pushed an additional commit which fixes the `super-linter` config for this repo and it looks like it's green now.

2021-04-10 09:21 UTC, monotek approved these changes

2021-04-10 09:22 UTC, monotek requested changes
Thanks. But could you please sign Our commits so the dco check passes?

https://github.com/kokuwaio/helm-charts/pull/71/checks?check_run_id=2309129715

2021-04-10 16:51 UTC, Ghazgkull commented
@monotek Oh I see. I had signed the first one, but not the second. I've squashed the commits and pushed a single commit now which should pass the DCO check.

2021-04-10 17:48 UTC, monotek approved these changes

2021-04-10 17:48 UTC, merged